INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita) VALUES ("01","04/08/2017","AS Monaco","Toulouse FC", "3","2");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita) VALUES ("01","05/08/2017","Paris Saint Germain","Amiens SC", "2","0" );
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("01","05/08/2017","AS Saint Etienne","OGC Nice", "1","0" );
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("01","05/08/2017","ESTAC Troyes","Stade Rennes", "1","1" );
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("01","05/08/2017","FC Metz","EA Guingamp", "1","3" );
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("01","05/08/2017","Montpellier HSC","SM Caen", "1","0" );
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("01","05/08/2017","Olympique Lyon","RC Strasbourg", "4","0" );
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("01","06/08/2017","Lille OSC","FC Nantes", "3","0" );
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("01","06/08/2017","Angers SCO","Girondins Bordeaux", "2","2" );
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("01","06/08/2017","Olympique Marseille","Dijon FCO", "3","0" );

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("02","11/08/2017","OGC Nice","ESTAC Troyes","1","2");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("02","11/08/2017","Stade Rennes","Olympique Lyon","1","2");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("02","12/08/2017","FC Nantes","Olympique Marseille","0","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("02","12/08/2017","Toulouse FC","Montpellier HSC","1","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("02","12/08/2017","Girondins Bordeaux","FC Metz","2","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("02","12/08/2017","Amiens SC","Angers SCO","0","2" );
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("02","12/08/2017","SM Caen","AS Saint Etienne","0","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("02","13/08/2017","RC Strasbourg","Lille OSC","3","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("02","13/08/2017","Dijon FCO","AS Monaco","1","4" );
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("02","13/08/2017","EA Guingamp","Paris Saint Germain","0","3");

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("03","18/08/2017","FC Metz","AS Monaco","0","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("03","19/08/2017","Olympique Lyon","Girondins Bordeaux","3","3");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("03","19/08/2017","AS Saint Etienne","Amiens SC","3","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("03","19/08/2017","ESTAC Troyes","FC Nantes","0","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("03","19/08/2017","Montpellier HSC","RC Strasbourg","1","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("03","19/08/2017","OGC Nice","EA Guingamp","2","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("03","19/08/2017","Stade Rennes","Dijon FCO","2","2");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("03","20/08/2017","Lille OSC","SM Caen","0","2");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("03","20/08/2017","Olympique Marseille","Angers SCO","1","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("03","20/08/2017","Paris Saint Germain","Toulouse FC","6","2");

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("04","25/08/2017","Paris Saint Germain","AS Saint Etienne","3","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("04","26/08/2017","FC Nantes","Olympique Lyon","0","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("04","26/08/2017","Dijon FCO","Montpellier HSC","2","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("04","26/08/2017","Toulouse FC","Stade Rennes","3","2");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("04","26/08/2017","Girondins Bordeaux","ESTAC Troyes","2","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("04","26/08/2017","Amiens SC","OGC Nice","3","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("04","26/08/2017","SM Caen","FC Metz","1","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("04","27/08/2017","EA Guingamp","RC Strasbourg","2","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("04","27/08/2017","Angers SCO","Lille OSC","1","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("04","27/08/2017","AS Monaco","Olympique Marseille","6","1");

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("05","08/09/2017","Lille OSC","Girondins Bordeaux","0","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("05","08/09/2017","FC Metz","Paris Saint Germain","1","5");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("05","09/09/2017","OGC Nice","AS Monaco","4","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("05","09/09/2017","ESTAC Troyes","Toulouse FC","0","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("05","09/09/2017","Montpellier HSC","FC Nantes","0","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("05","09/09/2017","RC Strasbourg","Amiens SC","0","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("05","09/09/2017","SM Caen","Dijon FCO","2","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("05","10/09/2017","AS Saint Etienne","Angers SCO","1","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("05","10/09/2017","Olympique Lyon","EA Guingamp","2","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("05","10/09/2017","Olympique Marseille","Stade Rennes","1","3");

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("06","15/09/2017","Toulouse FC","Girondins Bordeaux","0","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("06","16/09/2017","AS Monaco","RC Strasbourg","3","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("06","16/09/2017","Dijon FCO","AS Saint Etienne","0","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("06","16/09/2017","EA Guingamp","Lille OSC","1","0" );
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("06","16/09/2017","ESTAC Troyes","Montpellier HSC","0","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("06","16/09/2017","FC Nantes","SM Caen","1","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("06","17/09/2017","Amiens SC","Olympique Marseille","0","2");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("06","17/09/2017","Angers SCO","FC Metz","0","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("06","17/09/2017","Stade Rennes","OGC Nice","0","1" );
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("06","17/09/2017","Paris Saint Germain","Olympique Lyon","2","0");

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("07","22/09/2017","OGC Nice","Angers SCO","2","2");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("07","22/09/2017","Lille OSC","AS Monaco","0","4");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("07","23/09/2017","Montpellier HSC","Paris Saint Germain","0","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("07","23/09/2017","FC Metz","ESTAC Troyes","0","1" );
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("07","23/09/2017","Girondins Bordeaux","EA Guingamp","3","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("07","23/09/2017","Olympique Lyon","Dijon FCO","3","3");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("07","23/09/2017","SM Caen","Amiens SC","1","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("07","24/09/2017","AS Saint Etienne","Stade Rennes","2","2");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("07","24/09/2017","RC Strasbourg","FC Nantes","1","2");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("07","24/09/2017","Olympique Marseille","Toulouse FC","2","0");

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("08","29/09/2017","AS Monaco","Montpellier HSC","1","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("08","30/09/2017","Paris Saint Germain","Girondins Bordeaux","6","2");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("08","30/09/2017","Dijon FCO","RC Strasbourg","1","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("08","30/09/2017","EA Guingamp","Toulouse FC","1","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("08","30/09/2017","FC Nantes","FC Metz","1","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("08","30/09/2017","Stade Rennes","SM Caen","0","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("08","01/10/2017","ESTAC Troyes","AS Saint Etienne","2","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("08","01/10/2017","Angers SCO","Olympique Lyon","3","3");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("08","01/10/2017","OGC Nice","Olympique Marseille","2","4");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("08","20/11/2017","Amiens SC","Lille OSC","3","0");

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("09","13/10/2017","Olympique Lyon","AS Monaco","3","2");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("09","14/10/2017","Dijon FCO","Paris Saint Germain","1","2");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("09","14/10/2017","AS Saint Etienne","FC Metz","3","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("09","14/10/2017","EA Guingamp","Stade Rennes","2","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("09","14/10/2017","Toulouse FC","Amiens SC","1","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("09","14/10/2017","Lille OSC","ESTAC Troyes","2","2");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("09","14/10/2017","SM Caen","Angers SCO","0","2");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("09","15/10/2017","Girondins Bordeaux","FC Nantes","1","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("09","15/10/2017","Montpellier HSC","OGC Nice","2","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("09","15/10/2017","RC Strasbourg","Olympique Marseille","3","3");

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("10","20/10/2017","AS Saint Etienne","Montpellier HSC","0","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("10","21/10/2017","AS Monaco","SM Caen","2","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("10","21/10/2017","FC Metz","Dijon FCO","1","2");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("10","21/10/2017","FC Nantes","EA Guingamp","2","1" );
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("10","21/10/2017","Amiens SC","Girondins Bordeaux","1","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("10","21/10/2017","Angers SCO","Toulouse FC","0","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("10","21/10/2017","Stade Rennes","Lille OSC","1","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("10","22/10/2017","OGC Nice","RC Strasbourg","1","2");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("10","22/10/2017","ESTAC Troyes","Olympique Lyon","0","5");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("10","22/10/2017","Olympique Marseille","Paris Saint Germain","2","2");

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("11","27/10/2017","Paris Saint Germain","OGC Nice","3","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("11","28/10/2017","Girondins Bordeaux","AS Monaco","0","2");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("11","28/10/2017","Dijon FCO","FC Nantes","1","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("11","28/10/2017","EA Guingamp","Amiens SC","1","1" );
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("11","28/10/2017","Montpellier HSC","Stade Rennes","0","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("11","28/10/2017","RC Strasbourg","Angers SCO","2","2");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("11","28/10/2017","SM Caen","ESTAC Troyes","1","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("11","29/10/2017","Olympique Lyon","FC Metz","2","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("11","29/10/2017","Toulouse FC","AS Saint Etienne","0","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("11","29/10/2017","Lille OSC","Olympique Marseille","0","1");

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("12","03/11/2017","Stade Rennes","Girondins Bordeaux","1","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("12","04/11/2017","Angers SCO","Paris Saint Germain","0","5");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("12","04/11/2017","AS Monaco","EA Guingamp","6","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("12","04/11/2017","ESTAC Troyes","RC Strasbourg","3","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("12","04/11/2017","FC Nantes","Toulouse FC","2","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("12","04/11/2017","Montpellier HSC","Amiens SC","1","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("12","05/11/2017","OGC Nice","Dijon FCO","1","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("12","05/11/2017","FC Metz","Lille OSC","0","3");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("12","05/11/2017","Olympique Marseille","SM Caen","5","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("12","05/11/2017","AS Saint Etienne","Olympique Lyon","0","5");

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("13","17/11/2017","Lille OSC","AS Saint Etienne","3","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("13","17/11/2017","Amiens SC","AS Monaco","1","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("13","18/11/2017","Paris Saint Germain","FC Nantes","4","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("13","18/11/2017","Dijon FCO","ESTAC Troyes","3","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("13","18/11/2017","EA Guingamp","Angers SCO","1","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("13","18/11/2017","Toulouse FC","FC Metz","0","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("13","18/11/2017","RC Strasbourg","Stade Rennes","2","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("13","19/11/2017","SM Caen","OGC Nice","1","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("13","19/11/2017","Olympique Lyon","Montpellier HSC","0","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("13","19/11/2017","Girondins Bordeaux","Olympique Marseille","1","1");

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("14","24/11/2017","AS Saint Etienne","RC Strasbourg","2","2");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("14","25/11/2017","Stade Rennes","FC Nantes","2","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("14","25/11/2017","Dijon FCO","Toulouse FC","3","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("14","25/11/2017","ESTAC Troyes","Angers SCO","3","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("14","25/11/2017","FC Metz","Amiens SC","0","2");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("14","25/11/2017","Montpellier HSC","Lille OSC","3","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("14","25/11/2017","SM Caen","Girondins Bordeaux","1","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("14","26/11/2017","OGC Nice","Olympique Lyon","0","5");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("14","26/11/2017","Olympique Marseille","EA Guingamp","1","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("14","26/11/2017","AS Monaco","Paris Saint Germain","1","2");

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("15","28/11/2017","RC Strasbourg","SM Caen","0","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("15","28/11/2017","Amiens SC","Dijon FCO","2","1");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("15","28/11/2017","Girondins Bordeaux","AS Saint Etienne","3","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("15","29/11/2017","EA Guingamp","Montpellier HSC","0","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("15","29/11/2017","FC Metz","Olympique Marseille","0","3");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("15","29/11/2017","FC Nantes","AS Monaco","1","0");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("15","29/11/2017","Toulouse FC","OGC Nice","1","2");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("15","29/11/2017","Olympique Lyon","Lille OSC","1","2");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("15","29/11/2017","Angers SCO","Stade Rennes","1","2");
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("15","29/11/2017","Paris Saint Germain","ESTAC Troyes","2","0");	

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("16","01/12/2017","Dijon FCO","Girondins Bordeaux","3","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("16","02/12/2017","RC Strasbourg","Paris Saint Germain","2","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("16","02/12/2017","AS Monaco","Angers SCO","1","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("16","02/12/2017","ESTAC Troyes","EA Guingamp","0","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("16","02/12/2017","OGC Nice","FC Metz","3","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("16","02/12/2017","Lille OSC","Toulouse FC","1","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("16","02/12/2017","Stade Rennes","Amiens SC","2","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("16","03/12/2017","AS Saint Etienne","FC Nantes","1","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("16","03/12/2017","SM Caen","Olympique Lyon","1","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("16","03/12/2017","Montpellier HSC","Olympique Marseille","1","1");		


INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("17","08/12/2017","Girondins Bordeaux","RC Strasbourg","0","3");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("17","09/12/2017","Paris Saint Germain","Lille OSC","3","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("17","09/12/2017","AS Monaco","ESTAC Troyes","3","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("17","09/12/2017","EA Guingamp","Dijon FCO","4","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("17","09/12/2017","FC Metz","Stade Rennes","1","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("17","09/12/2017","Toulouse FC",	"SM Caen","2","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("17","09/12/2017","Angers SCO","Montpellier HSC","1","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("17","10/12/2017","Amiens SC","Olympique Lyon","1","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("17","10/12/2017","FC Nantes","OGC Nice","1","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("17","10/12/2017","Olympique Marseille","AS Saint Etienne","3","0");		

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("18","15/12/2017","AS Saint Etienne","AS Monaco","0","4");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("18","16/12/2017","Stade Rennes","Paris Saint Germain","1","4");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("18","16/12/2017","Dijon FCO","Lille OSC","3","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("18","16/12/2017","ESTAC Troyes","Amiens SC","1","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("18","16/12/2017","Montpellier HSC","FC Metz","1","3");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("18","16/12/2017","RC Strasbourg","Toulouse FC","2","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("18","16/12/2017","SM Caen","EA Guingamp","0","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("18","17/12/2017","FC Nantes","Angers SCO","1","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("18","17/12/2017","OGC Nice","Girondins Bordeaux","1","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("18","17/12/2017","Olympique Lyon","Olympique Marseille","2","0");		

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("19","20/12/2017","AS Monaco","Stade Rennes","2","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("19","20/12/2017","EA Guingamp","AS Saint Etienne","2","1" );		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("19","20/12/2017","FC Metz","RC Strasbourg","3","0" );		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("19","20/12/2017","Toulouse FC",	"Olympique Lyon","1","2" );		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("19","20/12/2017","Girondins Bordeaux","Montpellier HSC","0","2" );		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("19","20/12/2017","Olympique Marseille","ESTAC Troyes","3","1" );		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("19","20/12/2017","Lille OSC","OGC Nice","1","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("19","20/12/2017","Paris Saint Germain","SM Caen","3","1" );		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("19","20/12/2017","Amiens SC","FC Nantes","0","1" );		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("19","20/12/2017","Angers SCO","Dijon FCO","2","1" );		

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("20","12/01/2018","RC Strasbourg","EA Guingamp","0","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("20","13/01/2018","Stade Rennes","Olympique Marseille","0","3");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("20","13/01/2018","Dijon FCO","FC Metz","1","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("20","13/01/2018","ESTAC Troyes","Girondins Bordeaux","0","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("20","13/01/2018","Montpellier HSC","AS Monaco","0","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("20","13/01/2018","OGC Nice","Amiens SC","1","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("20","13/01/2018","SM Caen","Lille OSC",	"0","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("20","14/01/2018","AS Saint Etienne","Toulouse FC","2","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("20","14/01/2018","Olympique Lyon","Angers SCO","1","1" );		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("20","14/01/2018","FC Nantes","Paris Saint Germain","0","1" );		

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("21","16/01/2018","Girondins Bordeaux","SM Caen","0","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("21","16/01/2018","Olympique Marseille","RC Strasbourg","2","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("21","16/01/2018","AS Monaco","OGC Nice","2","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("21","17/01/2018","EA Guingamp","Olympique Lyon","0","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("21","17/01/2018","FC Metz","AS Saint Etienne","3","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("21","17/01/2018","Toulouse FC","FC Nantes","1","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("21","17/01/2018","Lille OSC","Stade Rennes","1","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("21","17/01/2018","Amiens SC","Montpellier HSC","1","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("21","17/01/2018","Angers SCO","ESTAC Troyes","3","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("21","17/01/2018","Paris Saint Germain","Dijon FCO","8","0");
		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("22","19/01/2018","SM Caen","Olympique Marseille","0","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("22","20/01/2018","FC Nantes","Girondins Bordeaux","0","1" );		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("22","20/01/2018","ESTAC Troyes","Lille OSC","1","0" );		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("22","20/01/2018","Montpellier HSC","Toulouse FC","2","1" );		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("22","20/01/2018","RC Strasbourg","Dijon FCO","3","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("22","20/01/2018","Amiens SC","EA Guingamp","3","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("22","20/01/2018","Stade Rennes","Angers SCO","1","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("22","21/01/2018","OGC Nice","AS Saint Etienne","1","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("22","21/01/2018","AS Monaco","FC Metz","3","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("22","21/01/2018","Olympique Lyon","Paris Saint Germain","2","1");		

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("23","26/01/2018","Dijon FCO","Stade Rennes","2","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("23","27/01/2018","Paris Saint Germain","Montpellier HSC","4","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("23","27/01/2018","AS Saint Etienne","SM Caen","2","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("23","27/01/2018","EA Guingamp","FC Nantes","0","3");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("23","27/01/2018","FC Metz","OGC Nice","2","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("23","27/01/2018","Toulouse FC","ESTAC Troyes","1","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("23","27/01/2018","Angers SCO","Amiens SC","1","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("23","28/01/2018","Lille OSC","RC Strasbourg","2","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("23","28/01/2018","Girondins Bordeaux","Olympique Lyon","3","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("23","28/01/2018","Olympique Marseille","AS Monaco","2","2");		

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("24","02/02/2018","Olympique Marseille","FC Metz","6","3");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("24","03/02/2018","Lille OSC","Paris Saint Germain","0","3");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("24","03/02/2018","Montpellier HSC","Angers SCO","2","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("24","03/02/2018","OGC Nice","Toulouse FC","0","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("24","03/02/2018","RC Strasbourg","Girondins Bordeaux","0","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("24","03/02/2018","Amiens SC","AS Saint Etienne","0","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("24","04/02/2018","Stade Rennes","EA Guingamp","0","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("24","04/02/2018","SM Caen","FC Nantes","3","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("24","04/02/2018","AS Monaco","Olympique Lyon","3","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("24","20/02/2018","ESTAC Troyes","Dijon FCO","0","0");		

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("25","09/02/2018","AS Saint Etienne","Olympique Marseille","2","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("25","10/02/2018","Toulouse FC","Paris Saint Germain","0","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("25","10/02/2018","Dijon FCO","OGC Nice","3","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("25","10/02/2018","EA Guingamp","SM Caen","0","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("25","10/02/2018","FC Metz","Montpellier HSC","0","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("25","10/02/2018","Girondins Bordeaux","Amiens SC","3","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("25","10/02/2018","Angers SCO","AS Monaco","0","4");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("25","11/02/2018","RC Strasbourg","ESTAC Troyes","2","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("25","11/02/2018","FC Nantes","Lille OSC","2","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("25","11/02/2018","Olympique Lyon","Stade Rennes","0","2");	
	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("26","16/02/2018","AS Monaco","Dijon FCO","4","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("26","17/02/2018","Paris Saint Germain","RC Strasbourg","5","2" );		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("26","17/02/2018","ESTAC Troyes","FC Metz","1","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("26","17/02/2018","Montpellier HSC","EA Guingamp","1","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("26","17/02/2018","Amiens SC","Toulouse FC","0","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("26","17/02/2018","Angers SCO","AS Saint Etienne","0","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("26","17/02/2018","SM Caen","Stade Rennes","2","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("26","18/02/2018","OGC Nice","FC Nantes","1","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("26","18/02/2018","Lille OSC","Olympique Lyon","2","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("26","18/02/2018","Olympique Marseille","Girondins Bordeaux","1","0");	
	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("27","23/02/2018","RC Strasbourg","Montpellier HSC","0","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("27","24/02/2018","Toulouse FC",	"AS Monaco","3","3");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("27","24/02/2018","Dijon FCO","SM Caen","2","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("27","24/02/2018","EA Guingamp","FC Metz","2","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("27","24/02/2018","FC Nantes","Amiens SC","0","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("27","24/02/2018","Lille OSC","Angers SCO","1","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("27","24/02/2018","Stade Rennes","ESTAC Troyes","2","0" );		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("27","25/02/2018","Girondins Bordeaux","OGC Nice","0","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("27","25/02/2018","Olympique Lyon","AS Saint Etienne","1","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("27","25/02/2018","Paris Saint Germain","Olympique Marseille","3","0");	
	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("28","02/03/2018","OGC Nice","Lille OSC","2","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("28","02/03/2018","AS Monaco","Girondins Bordeaux","2","1" );		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("28","03/03/2018","ESTAC Troyes","Paris Saint Germain","0","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("28","02/03/2018","AS Saint Etienne","Dijon FCO",	"2","2" );		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("28","02/03/2018","FC Metz","Toulouse FC","1","1" );		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("28","02/03/2018","Amiens SC","Stade Rennes","0","2" );		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("28","02/03/2018","Angers SCO","EA Guingamp","3","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("28","04/03/2018","SM Caen","RC Strasbourg","2","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("28","04/03/2018","Montpellier HSC","Olympique Lyon","1","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("28","04/03/2018","Olympique Marseille","FC Nantes","1","1");
		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("29","09/03/2018","RC Strasbourg","AS Monaco","1","3");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("29","10/03/2018","Paris Saint Germain","FC Metz","5","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("29","10/03/2018","Dijon FCO","Amiens SC","1","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("29","10/03/2018","FC Nantes","ESTAC Troyes","1","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("29","10/03/2018","Girondins Bordeaux","Angers SCO","0","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("29","10/03/2018","Lille OSC","Montpellier HSC","1","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("29","10/03/2018","Stade Rennes","AS Saint Etienne","1","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("29","11/03/2018","EA Guingamp","OGC Nice","2","5");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("29","11/03/2018","Olympique Lyon","SM Caen","1","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("29","11/03/2018","Toulouse FC","Olympique Marseille","1","2");		

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("30","16/03/2018","AS Monaco","Lille OSC","2","1" );		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("30","17/03/2018","Girondins Bordeaux","Stade Rennes","0","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("30","17/03/2018","Toulouse FC",	"RC Strasbourg","2","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("30","17/03/2018","Montpellier HSC","Dijon FCO","2","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("30","17/03/2018","Amiens SC","ESTAC Troyes","1","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("30","17/03/2018","Angers SCO","SM Caen","3","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("30","18/03/2018","OGC Nice","Paris Saint Germain","1","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("30","17/03/2018","FC Metz","FC Nantes","1","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("30","17/03/2018","AS Saint Etienne","EA Guingamp","2","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("30","17/03/2018","Olympique Marseille","Olympique Lyon","2","3");		

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("31","14/03/2018","Paris Saint Germain","Angers SCO","2","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("31","31/03/2018","Dijon FCO","Olympique Marseille","1","3");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("31","01/04/2018","EA Guingamp","Girondins Bordeaux","2","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("31","01/04/2018","ESTAC Troyes","OGC Nice","0","2" );		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("31","01/04/2018","FC Nantes","AS Saint Etienne","0","3");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("31","01/04/2018","Lille OSC","Amiens SC","0","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("31","01/04/2018","RC Strasbourg","FC Metz","2","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("31","01/04/2018","SM Caen","Montpellier HSC","1","3");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("31","01/04/2018","Olympique Lyon","Toulouse FC","2","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("31","04/04/2018","Stade Rennes","AS Monaco","1","1");		

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("32","06/04/2018","AS Saint Etienne","Paris Saint Germain","1","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("32","07/04/2018","AS Monaco","FC Nantes","2","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("32","07/04/2018","EA Guingamp","ESTAC Troyes","4","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("32","07/04/2018","Toulouse FC","Dijon FCO","0","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("32","07/04/2018","Girondins Bordeaux","Lille OSC","2","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("32","07/04/2018","Amiens SC","SM Caen","3","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("32","07/04/2018","Angers SCO","RC Strasbourg","1","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("32","08/04/2018","OGC Nice","Stade Rennes","1","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("32","08/04/2018","FC Metz","Olympique Lyon","0","5");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("32","08/04/2018","Olympique Marseille","Montpellier HSC","0","0");		

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("33","13/04/2018","Angers SCO","OGC Nice","1","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("33","14/04/2018","Olympique Lyon","Amiens SC","3","0");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("33","14/04/2018","FC Nantes","Dijon FCO","1","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("33","14/04/2018","Lille OSC","EA Guingamp","2","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("33","14/04/2018","Stade Rennes","FC Metz","1","2");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("33","14/04/2018","RC Strasbourg","AS Saint Etienne","0","1");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("33","15/04/2018","Montpellier HSC","Girondins Bordeaux","1","3");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("33","15/04/2018","ESTAC Troyes","Olympique Marseille","2","3");		
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("33","15/04/2018","Paris Saint Germain",	"AS Monaco","7","1");	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("33","25/04/201","SM Caen","Toulouse FC","0","0");	

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("34","20/04/201","FC Nantes","Stade Rennes","1","0");	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("34","20/04/201","Dijon FCO","Olympique Lyon","1","1");	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("34","21/04/201","Olympique Marseille","Lille OSC","4","0");	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("34","21/04/201","EA Guingamp","AS Monaco","2","0");	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("34","21/04/201","FC Metz","SM Caen","0","0");	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("34","21/04/201","Toulouse FC","Angers SCO","1","0");	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("34","21/04/201","Amiens SC","RC Strasbourg","1","0");	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("34","22/04/201","OGC Nice","Montpellier HSC","0","0");	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("34","22/04/201","AS Saint Etienne","ESTAC Troyes","0","1");	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("34","22/04/201","Girondins Bordeaux","Paris Saint Germain","0","0");	

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("35","27/04/201","Montpellier HSC","AS Saint Etienne","0","1");	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("35","28/04/201","Olympique Lyon","FC Nantes","1","0");	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("35","28/04/201","AS Monaco","Amiens SC","0","0");	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("35","28/04/201","ESTAC Troyes","SM Caen","2","1");	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("35","28/04/201","Girondins Bordeaux","Dijon FCO","1","0");	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("35","28/04/201","Lille OSC","FC Metz","2","0");	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("35","28/04/201","RC Strasbourg","OGC Nice","1","0");	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("35","29/04/201","Stade Rennes","Toulouse FC","1","1");	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("35","29/04/201","Angers SCO","Olympique Marseille","0","1");	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("35","29/04/201","Paris Saint Germain","EA Guingamp","0","1");	

INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("36","04/05/201","Amiens SC","Paris Saint Germain","0","1");	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("36","06/05/201","AS Saint Etienne","Girondins Bordeaux","1","2");	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("36","06/05/201","Olympique Lyon","ESTAC Troyes","2","0");	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("36","06/05/201","Dijon FCO","EA Guingamp","1","0");	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("36","06/05/201","FC Metz","Angers SCO","1","0");	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("36","06/05/201","FC Nantes","Montpellier HSC","0","0");	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("36","06/05/201","Toulouse FC","Lille OSC","2","1");	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("36","06/05/201","SM Caen","AS Monaco","1","1");	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("36","06/05/201","Stade Rennes","RC Strasbourg","1","0");	
INSERT INTO partidos (Jornada, Fecha, Local, Visita, GolesLocal, GolesVisita)  VALUES ("36","06/05/201","Olympique Marseille","OGC Nice","1","1");		